### ISSUE TITLE
The "from" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by DavidOliver** [mischnic/parcel-namer-preserve-structure#6]
I'm using Parcel 2 beta 1.

`.parcelrc`:

```
{
  "extends": ["@parcel/config-default"],
  "namers": ["@mischnic/parcel-namer-preserve-structure", "..."],
  "transformers": {
    "*.{png,jpg,svg,gif,webp}": ["@parcel/transformer-raw"]
  }
}
```

```
  "devDependencies": {
    "@mischnic/parcel-namer-preserve-structure": "^0.1.2",
    "parcel": "^2.0.0-beta.1",
```

`npx parcel build --no-autoinstall --no-source-maps --dist-dir "web/build" "src/entry.html"`

```
🚨 Build failed.
@mischnic/parcel-namer-preserve-structure: The "from" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.relative (path.js:1053:5)
    at nameFromContent (/project/node_modules/@mischnic/parcel-namer-preserve-structure/index.js:119:16)
    at Object.name (/project/node_modules/@mischnic/parcel-namer-preserve-structure/index.js:88:16)
    at BundlerRunner.nameBundle (/project/node_modules/@parcel/core/lib/BundlerRunner.js:181:39)
    at /project/node_modules/@parcel/core/lib/BundlerRunner.js:169:50
    at Array.map (<anonymous>)
    at BundlerRunner.nameBundles (/project/node_modules/@parcel/core/lib/BundlerRunner.js:169:31)
    at async BundlerRunner.bundle (/project/node_modules/@parcel/core/lib/BundlerRunner.js:134:5)
    at async Parcel.build (/project/node_modules/@parcel/core/lib/Parcel.js:370:25)
```

**Comment by dacmail** [comment]
Did you resolve this? I get the same error:

I'm using Parcel 2.0.0, node v16.11.1 and npm 8.0.0


```
@mischnic/parcel-namer-preserve-structure: The "from" argument must be of type string. Received undefined

   TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
  at new NodeError (node:internal/errors:371:5)
  at validateString (node:internal/validators:119:11)
  at Object.relative (node:path:1191:5)
  at nameFromContent (/Users/dac/Code/bag/node_modules/@mischnic/parcel-namer-preserve-structure/index.js:119:16)
  at Object.name (/Users/dac/Code/bag/node_modules/@mischnic/parcel-namer-preserve-structure/index.js:88:16)
  at BundlerRunner.nameBundle (/Users/dac/Code/bag/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:355:39)
  at /Users/dac/Code/bag/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:331:50
  at Array.map (<anonymous>)
  at BundlerRunner.nameBundles (/Users/dac/Code/bag/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:331:31)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by DavidOliver** [comment]
@dacmail, no, I switched to Snowpack.
